import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FeedbackService } from '../../../shared/data/feedback.service';
import { Feedback } from '../../../models/feedback';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent implements OnInit {
  eventId!: number;
  comments: Feedback[] = [];
  newComment: string = '';
  isLoading: boolean = false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private feedbackService: FeedbackService
  ) { }

  ngOnInit(): void {
    // Get event ID from route parameters
    this.eventId = +this.route.snapshot.paramMap.get('id')!;
    this.loadComments();
  }

loadComments(): void {
  this.isLoading = true;
  this.feedbackService.getFeedbackByEventId(this.eventId).subscribe({
    next: (comments) => {
      this.comments = comments;
      console.log('Loaded comments:', comments); // Add this line to debug
      this.isLoading = false;
    },
    error: (error) => {
      console.error('Error loading comments:', error);
      this.isLoading = false;
    }
  });
}

  addComment(): void {
    if (this.newComment.trim()) {
      const feedback: Feedback = {
        id: 0, // Will be auto-generated by JSON server
        eventId: this.eventId,
        comment: this.newComment.trim(),
        date: new Date().toISOString(),
        // Add any other required properties from your Feedback model
        userName: 'User', // You can make this dynamic if you have user authentication
        userEmail: 'user@example.com' // Add if your model requires this
      };

      this.feedbackService.createFeedback(feedback).subscribe({
        next: (newFeedback) => {
          this.comments.push(newFeedback);
          this.newComment = '';
        },
        error: (error) => {
          console.error('Error adding comment:', error);
        }
      });
    }
  }

  goBack(): void {
    // Navigate back to events page - adjust the route as needed
    this.router.navigate(['/events']);
  }

  deleteComment(commentId: number): void {
    if (confirm('Are you sure you want to delete this comment?')) {
      this.feedbackService.deleteone(commentId).subscribe({
        next: () => {
          this.comments = this.comments.filter(comment => comment.id !== commentId);
        },
        error: (error) => {
          console.error('Error deleting comment:', error);
        }
      });
    }
  }

  
}